version: "2"

services:
  kamus:
    image: kamus-dictionary
    build:
      dockerfile: Dockerfile
      context: kamus/
    environment:
      - DEBUG=0
      - SECRET_KEY=${KAMUS_SECRET_KEY}
      - DB_USER=${KAMUS_DB_USER}
      - DB_NAME=${KAMUS_DB_NAME}
      - DB_PASSWORD=${KAMUS_DB_PASSWORD}
      - DB_HOST=${KAMUS_DB_HOST}
      - DB_PORT=${KAMUS_DB_PORT}
        # TODO: move it outside docker-compose.yml
      - PYWIKIBOT_DIR=/tmp/pywikibot
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - static_volume:/code/kamus/staticfiles
      - ./kamus:/code/kamus
      - ${HOME}/docker/kamus/var/log:/var/log
    networks:
      - nginx-proxy
    restart: unless-stopped

  reverse-proxy:
    image: kamus-nginx
    build:
      dockerfile: Dockerfile
      context: nginx/
    expose:
      - "80"
    environment:
      - NGINX_PORT=80
      - VIRTUAL_HOST=${KAMUS_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_HOST=${KAMUS_HOST}
    volumes:
      - static_volume:/code/kamus/staticfiles
    links:
      - kamus
    networks:
      - nginx-proxy
    restart: unless-stopped

volumes:
  static_volume: {}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
