# Generated by Django 4.1 on 2022-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordwithtranslation",
            name="word",
            field=models.CharField(db_collation="utf8_bin", max_length=100),
        ),
    ]
