# Generated by Django 4.1 on 2022-08-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_wordwithtranslation_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_created_on", models.DateTimeField()),
                ("file_size", models.IntegerField()),
                ("file_path", models.CharField(max_length=200)),
                ("imported_on", models.DateTimeField()),
                ("translated_words", models.IntegerField()),
                ("total_words", models.IntegerField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.language"
                    ),
                ),
            ],
        ),
    ]
